[package]
name = "rend3-imgui"
version = "0.2.0"
authors = ["The rend3 Developers"]
edition = "2021"
description = "Imgui Render Routine for rend3"
readme = "../README.md"
license = "MIT OR Apache-2.0 OR Zlib"
repository = "https://github.com/BVE-Reborn/rend3"
keywords = ["3d", "graphics", "gpu", "renderer", "wgpu"]
categories = ["game-development", "graphics", "rendering", "rendering::engine"]
rust-version = "1.57"

[dependencies]
imgui = "0.8"
imgui-wgpu = { version = "0.18", git = "https://github.com/Yatekii/imgui-wgpu-rs.git", rev = "5ad9970820bceb2dd9041363fb7f7ba88300ad07" }
glam = "0.20.0"
rend3 = { version = "^0.2.0", path = "../rend3" }